#!/bin/bash
#
## @file		ocbootstrap
## @copyright		OpenCog Foundation (2012)
## @author		David Hart <dhart@opencog.org>
## @section DESCRIPTION	A script to create a chroot environment in which to run ocpkg 
## @section LICENSE	Permission to copy and modify is granted under the GPL
## @section REQUIREMENT	Any Linux distribution, run as root

DISTRO_MIRROR=http://archive.ubuntu.com/ubuntu
CHROOT_DISTRO=precise
ARCH=amd64
SELF_NAME=$(basename $0)
MAKE_JOBS=$(($PROCESSORS+0))

usage() {
  echo "Usage: $SELF_NAME [-a ARCH] [-p DISTRO_MIRROR] [DISTRO_NAME]"
}

while getopts ":a:p:" flag ; do
  case $flag in
    a)	ARCH="$OPTARG" ;;          
    p)	DISTRO_MIRROR="$OPTARG" ;;          
    j)	MAKE_JOBS="$OPTARG" ;;			#override auto-detected MAKE_JOBS
    \?)	usage ;;
  esac
done

shift $((OPTIND-1))

if [ $1 ] ; then CHROOT_DISTRO=$1 ; fi

CHROOT_DIR=/var/$CHROOT_DISTRO

if [ ! $(which debootstrap) ] ; then
  if [ $(which dpkg) ] ; then 
    wget http://ftp.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.39_all.deb
    dpkg -i debootstrap_1.0.39_all.deb
  else
    wget http://ftp.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.39.tar.gz
    tar zxvf debootstrap_1.0.39.tar.gz
    cd debootstrap-1.0.39/
    make devices.tar.gz
    export DEBOOTSTRAP_DIR=$(pwd)
    export PATH=$PATH:$DEBOOTSTRAP_DIR
  fi
fi

if [ ! -d "$CHROOT_DIR" ] ; then
  mkdir -p $CHROOT_DIR
  debootstrap --arch $ARCH $CHROOT_DISTRO $CHROOT_DIR $DISTRO_MIRROR
fi

mkdir -p $CHROOT_DIR/usr/local/bin
mkdir -p $CHROOT_DIR/usr/local/src/opencog

ln -f -P /etc/mtab $CHROOT_DIR/etc/mtab

mount -o bind /dev $CHROOT_DIR/dev
mount -o bind /proc $CHROOT_DIR/proc
mount -o bind /sys $CHROOT_DIR/sys
mount -o bind /tmp $CHROOT_DIR/tmp
mount -o bind /dev/pts $CHROOT_DIR/dev/pts
mount -o bind /var/cache/apt/archives $CHROOT_DIR/var/cache/apt/archives
mount -o bind /var/lib/apt/lists $CHROOT_DIR/var/lib/apt/lists
mount -o bind /usr/local/src/opencog $CHROOT_DIR/usr/local/src/opencog

echo "deb $DISTRO_MIRROR $CHROOT_DISTRO main universe" > $CHROOT_DIR/etc/apt/sources.list

chroot $CHROOT_DIR /usr/bin/apt-get update
chroot $CHROOT_DIR /usr/bin/apt-get -y install python-software-properties bzr sudo
chroot $CHROOT_DIR /usr/bin/bzr pull https://code.launchpad.net/~opencog-dev/opencog/ocpkg --use-existing-dir /usr/local/bin
chroot $CHROOT_DIR /bin/chmod ugo+rx /usr/local/bin/*
chroot $CHROOT_DIR /usr/local/bin/ocpkg -j$MAKE_JOBS
