#!/bin/bash
#
## @file		ocbootstrap
## @copyright		OpenCog Foundation (2012)
## @author		David Hart <dhart@opencog.org>
## @section DESCRIPTION	create a chroot environment in which to run ocpkg 
## @section LICENSE	Permission to copy and modify is granted under the GPL
## @section REQUIREMENT	any Debian/Ubuntu derived Linux disto
##			ocpkg must be in your path, e.g. /usr/local/bin/ocpkg

# Note: edit variables as needed to suit your architecture (i386 or amd64) and
#       closest Ubuntu mirror

ARCH=amd64
UBUNTU_MIRROR=http://archive.ubuntu.com/ubuntu

wget http://archive.ubuntu.com/ubuntu/pool/main/d/debootstrap/debootstrap_1.0.37_all.deb
dpkg -i debootstrap_1.0.37_all.deb
mkdir /var/precise
debootstrap --arch $ARCH precise /var/precise $UBUNTU_MIRROR

mkdir -p /var/precise/usr/local/bin
mkdir -p /var/precise/usr/local/src/opencog

ln -f -P /etc/mtab /var/precise/etc/mtab
ln -f -P `which ocpkg` /var/precise/usr/local/bin/ocpkg

mount -o bind /dev /var/precise/dev
mount -o bind /proc /var/precise/proc
mount -o bind /sys /var/precise/sys
mount -o bind /tmp /var/precise/tmp
mount -o bind /dev/pts /var/precise/dev/pts
mount -o bind /var/cache/apt/archives /var/precise/var/cache/apt/archives
mount -o bind /var/lib/apt/lists /var/precise/var/lib/apt/lists
mount -o bind /usr/local/src/opencog /var/precise/usr/local/src/opencog

echo "deb $UBUNTU_MIRROR precise main universe" > /var/precise/etc/apt/sources.list

chroot /var/precise /usr/bin/apt-get update
chroot /var/precise /usr/bin/apt-get -y install python-software-properties
chroot /var/precise /usr/local/bin/ocpkg -j1
