#!/bin/bash
#
## @file		ocpkg
## @copyright		OpenCog Foundation (2012)
## @author		David Hart <dhart@opencog.org>
## @section DESCRIPTION	A script to download, build, test, install and package OpenCog
## @section LICENSE	Permission to copy and modify is granted under the GPL
## @section REQUIREMENT	Ubuntu Linux 12.04 (precise pangolin)
## @section SEEALSO	ocbootstrap - install an Ubuntu chroot on any Linux distro
 
# This bash script is organized in sections:
# SECTION 1. Global variable setting
# SECTION 2. Command line option handling
# SECTION 3. Error handling & cleanup
# SECTION 4. Function definitions
# SECTION 5. Main program

# Notes:
# - terminal & editor are best set to a column width of 144+ characters 
#        (bash lines, dpkg lines and gcc lines can be long!)
# - this script executes fastest with a minimum of 4GB RAM, 4GB SWAP, /tmp on 4GB tmpfs
#        (real time overhead for CD repackaging without building OpenCog is about 5m)
# - test CD/DVD images using:
#        testdrive -u OpenCogLive.iso
#        kvm -cdrom OpenCogLive.iso -boot d -m 2048

# To do: 
# - add Launchpad & bzr-buildeb build options (for deb packaging)
#       http://developer.ubuntu.com/packaging/html/
# - add vmbuilder option for OpenStack & Amazon EC2 distribution 
#       https://help.ubuntu.com/11.04/serverguide/C/jeos-and-vmbuilder.html
#	https://launchpad.net/awsome (front-end for OpenStack providing the AWS API)
# - add PACKAGE_BUILD variables for incremental builds
# - add manifest rebuild to LiveCD/DVD
# - add priveledge separation when run as root (run make, etc., as real user)

# TODO (when code in amberj-ocpkg is merged with lp:ocpkg)
# 1. build_opencog_deb() copies debian/ from lp:~i-amber-jain/ocpkg/amberj-ocpkg. Change the code so that it does the same from lp:ocpkg
# 2. build_opencog_deb() deletes Gama's debian/ from lp:opencog. When lp:opencog's debian/ (in the root dir) is removed from lp:opencog, remove the appropriate line of code

# trap errors
set -e

###############################
# SECTION 1: GLOBAL VARIABLES #
###############################

declare -A PACKAGE_DESCRIPTION=(
  [local]="Local install with no packaging (default)"
   [demo]="LiveCD  ISO image ~700MB with OpenCog Demo (auto-starting)"
    [min]="LiveCD  ISO image ~700MB with OpenCog Server"
    [dev]="LiveDVD ISO image ~900MB with OpenCog Developement Environment"
    [kvm]="TBD Ubuntu KVM image with OpenCog Server"
 [demovm]="TBD Ubuntu VirtualBox image with OpenCog Unity3D proxy for demo"
   [debs]="TBD Ubuntu packages (deb files)"
    [ppa]="Launchpad Personal Package Archive (PPA)"
   [tool]="OpenCog related operations"
)

PATH_PREFIX=/usr/local
CURRENT_DIR=$(pwd)

if [ "$USER" == "root" ] ; then
 HOST_SOURCE_BRANCH=$PATH_PREFIX/src/opencog  
 HOST_BUILD_DIR=/tmp/opencog_build
else
 HOST_SOURCE_BRANCH=$CURRENT_DIR/opencog/src  
 HOST_BUILD_DIR=$CURRENT_DIR/opencog/build
fi

BZR_REVISION="last:1"

OUTPUT_ISO_NAME=OpenCogLive.iso 
OUTPUT_ISO_LOCATION=$CURRENT_DIR

DEFAULT_PACKAGE_TYPE=local		
DEFAULT_ADD_REPOSITORIES=true
DEFAULT_INSTALL_DEPENDENCIES=true	
DEFAULT_UPDATE_OPENCOG=true		
DEFAULT_BUILD_OPENCOG=true

UBUNTU_ISO=ubuntu-11.10-desktop-amd64.iso
UBUNTU_URL=http://releases.ubuntu.com/11.10/
UBUNTU_MD5SUM=62fb5d750c30a27a26d01c5f3d8df459
UBUNTU_ISO_IMAGE=$CURRENT_DIR/$UBUNTU_ISO #default location

UPDATE_OPENCOG=$DEFAULT_UPDATE_OPENCOG
SELF_NAME=$(basename $0)
# TODO Change all occurrences of octool with tool (?)
TOOL_NAME=octool

PROCESSORS=$(grep "^processor" /proc/cpuinfo | wc -l)
MAKE_JOBS=$(($PROCESSORS+0))

SQUASHFS_OPTIONS="-noDataCompression -noappend" #faster
SQUASHFS_OPTIONS="-noappend"

LIVE_SOURCE_BRANCH=$HOST_SOURCE_BRANCH
LIVE_BUILD_DIR=$HOST_BUILD_DIR

VERBOSE="-v"				#for mount, umount, rm, etc.
QUIET="-qq" 				#for apt-get

LIVE_DESKTOP_SOURCE="OpenCog Source Code"

REPOSITORIES="		
		ppa:opencog-dev/ppa \
		"
		#opencog-dev: cxxtest

PACKAGES_TOOLS="	
		squashfs-tools \
		genisoimage \
		"
		#aria2 \
		#qemu-kvm \
		#testdrive \

DEB_PACKAGES_TOOLS="	
		build-essential \
		packaging-dev \
		gnupg \
		pbuilder \
		ubuntu-dev-tools \
		bzr-builddeb \
		dh-make \
		bzr-builddeb \
		devscripts \
		"
		#apt-file

PACKAGES_FETCH="	
		bzr \
			"
		#bzr-rewrite \

PACKAGES_ADMIN="	
		apt-rdepends \
		synaptic \
		gdebi \
		epiphany-browser \
		"
PACKAGES_BUILD="	
		build-essential \
		cmake \
		cxxtest \
		rlwrap \
		libsdl-gfx1.2-dev \
		guile-1.8-dev \
		libicu-dev \
		libbz2-dev \
		python-dev \
		cython \
		python-zmq \
		python-matplotlib \
		python-nose \
		python-numpy \
		python-setuptools \
		python-distutils-extra \
		python-scipy \
		python-mock \
		libboost-all-dev \
		libssl-dev \
		libgsl0-dev \
		libexpat1-dev \
		libxmlrpc-c3-dev \
		unixodbc-dev \
		libxerces-c2-dev \
		libcurl4-gnutls-dev \
		tcl-dev \
		tcsh \
		uuid-dev \
		libzmq-dev \
		libprotoc-dev \
		protobuf-compiler \
		doxygen \
		"
		#liblua5.1-0-dev \

PACKAGES_RUNTIME="	
		libboost-system1.46.1 \
		libboost-filesystem1.46.1 \
		libboost-thread1.46.1 \
		libboost-signals1.46.1 \
		libboost-regex1.46.1 \
		unixodbc \
		"
PACKAGES_DOC="		
		ubuntu-docs \
		libglib2.0-doc \
		libpango1.0-doc \
		libgtk-3-doc \
		texlive-latex-base-doc \
		python-doc \
		devhelp-common \
		texlive-doc-base \
		doxygen \
 		dot2tex \
		"
PACKAGES_REMOVE="	
		ubuntu-desktop \
		example-content \
		software-center \
		app-install-data \
		locales \
		libqtwebkit4 \
		openjdk-6-jre-headless \
		openjdk-6-jre \
		openjdk-7-jre \
		python-twisted-core \
		texlive-binaries \
		luatex \
		ubiquity \
		rhythmbox \
		rhythmbox-data \
		empathy \
		empathy-common \
		libtelepathy-glib0 \
		firefox \
		thunderbird \
		inkscape \
		libreoffice-core \
		gimp-data \
		gimp-help-common \
		evolution-data-server \
		gnome-games-common \
		gnome-games-data \
		aisleriot \
		ibus-table \
		ibus-table-extraphrase \
		libchewing3-data \
		deja-dup \
		banshee \
		gwibber \
		oneconf \
		shotwell \
		ubuntuone-client \
		python-ubuntuone-client \
		vim-runtime \
		gnome-orca \
		libgweather-common \
		simple-scan \
		sane-utils \
		printer-driver-hpcups \
		printer-driver-hpijs \
		printer-driver-foo2zjs \
		hplip \
		hplip-data \
		libgutenprint2 \
		foo2zjs \
		colord \
		libsane \
		mono-runtime \
		samba-common \
		gnome-user-guide \
		ure \
		smbclient \
		indicator-messages \
		ubuntuone-client-gnome \
		geoip-database \
		libopencc1 \
		fonts-arphic-bsmi00lp \
		fonts-arphic-gbsn00lp \
		fonts-arphic-bkai00mp \
		fonts-arphic-gkai00mp \
		lmodern \
		culmus \
		fonts-nanum \
		fonts-nanum-extra \
		fonts-nanum-coding \
		ttf-nanum-coding \
		ttf-indic-fonts-core \
		ttf-devanagari-fonts \
		ttf-wqy-microhei \
		fonts-takao-pgothic \
		cmap-adobe-japan1 \
		anthy-common \
		m17n-db \
		libhangul-data \
		libpurple0 \
		brltty \
		liblouis-data \
		libwebkitgtk-1.0-0 \
		libwebkitgtk-1.0-common \
		"
		#ubuntu-wallpapers \
		#this stuff is for Unity 2D, but Ubuntu fails to login without it
		#libqtgui4 \
		#libqt4-core \
		#libqt4-xmlpatterns \
		#libwebkitgtk-3.0-0 \
		#language-pack-pt-base \
		#language-pack-es-base \
		#language-pack-xh-base \
		#language-pack-zh-hans \
		#language-pack-de-base \
		#language-pack-fr-base \
		#language-pack-ca-base \
		#language-pack-el-base \
		#language-pack-sv-base \
		#language-pack-ru-base \
		#language-pack-gnome-zh-hans-base \
		#language-pack-kde-zh-hans-base \
		# NOTES
		# apps listed first, then libraries that they depend upon which will 
		#	also uninstall other stuff
		#	ubiquity - graphical Ubuntu installer that runs on boot
		#  23MB app-install-data (ubuntu software center)
		#  22MB ubuntu-docs (desktop docs)
		#  44MB thunderbird
		#  26MB amarok
		# 200MB libreoffice
		#  45MB smbclient
PACKAGES_EXDEV="	
		autoconf automake autotools-dev \
		blt \
		comerr-dev \
		dpkg-dev \
		emacsen-common \
		fakeroot \
		gettext \
		gdb \
		g++-4.6 \
		gcc-4.6 \
		krb5-multidev \
		libc6-dev \
		libdpkg-perl \
		libdpkg-perl \
		libgcrypt11-dev \
		libglade2-0 \
		libgnutls-dev \
		libgpg-error-dev \
		libgssrpc4 \
		libidn11-dev \
		libalgorithm-diff-perl \
		libalgorithm-diff-xs-perl \
		libalgorithm-merge-perl \
		libkadm5clnt-mit8 \
		libkadm5srv-mit8 \
		libkrb5-dev \
		libldap2-dev \
		libltdl-dev \
		libstdc++6-4.6-dev \
		libtasn1-3-dev \
		libtimedate-perl \
		libtool \
		libunistring0 \
		libxss1 \
		make \
		manpages-dev \
		m4 \
		patch \
		python-glade2 \
		python-tk \
		tcl8.5 \
		tk8.5 \
		ttf-lyx \
		zlib1g-dev \
		python-bzrlib \
		linux-headers-generic \
		linux-headers-3.2.0-22 \
		"

###########################################
# SECTION 2: Command line option handling #
###########################################

# TODO: Update usage() [major changes were made to command line option handling]
usage() {
if [ "$SELF_NAME" != "$TOOL_NAME" ] ; then
  echo "Usage: $SELF_NAME [OPTIONS] [PACKAGE-TYPE]"
  echo "  PACKAGE-TYPES:"
  for key in ${!PACKAGE_DESCRIPTION[@]}; do
    echo "   " ${key} $'\t' "${PACKAGE_DESCRIPTION[$key]}"
  done
  echo "    (Live CD: Ubuntu ISO image ~700MB will be downloaded if none found.)"
  echo "  OPTIONS:"
  echo "    -i [filename]  ISO input  filename"
  echo "    -o [filename]  ISO output filename"
  echo "    -j [jobs]      override number of auto-detected make jobs"
  echo "    -n             supress bzr updates"
else 
  echo "Usage: $SELF_NAME OPTION"
  echo " -a Add software repositories"
  echo " -d Install build dependencies"
  echo " -u Update OpenCog source at $HOST_SOURCE_BRANCH"
  echo " -b Build OpenCog"
  echo " -t Test OpenCog"
fi 
exit 0
}

message() {
echo -e "\e[1;34m[$SELF_NAME] $MESSAGE\e[0m"
}

# Parse package type (e.g. "debs" for Ubuntu/Debian debs, "local" for building locally etc.)
if [ "$SELF_NAME" = "ocpkg" ] ; then
  PACKAGE_TYPE=$DEFAULT_PACKAGE_TYPE
  case "$1" in
    --debs|debs)
	  shift ; PACKAGE_TYPE="debs" ;;
	--dev|dev)
	  shift ; PACKAGE_TYPE="dev"	;;
	--demo|demo)
	  shift ; PACKAGE_TYPE="demo" ;;
	--kvm|kvm)
	  shift ; PACKAGE_TYPE="kvm" ;;
	--min|min)
	  shift ; PACKAGE_TYPE="min" ;;
	--local|local)
	  shift ; PACKAGE_TYPE="local" ;;
	--tool|tool)
	  shift ; PACKAGE_TYPE="tool" ;;
	*)
	  MESSAGE="Package type $1 not recognized." ; message ; usage ; exit 1 ;;
  esac
  MESSAGE="Package type: $PACKAGE_TYPE : ${PACKAGE_DESCRIPTION[$PACKAGE_TYPE]}" ; message
fi

if [ "$SELF_NAME" = "ocdebs" ] || [ "$PACKAGE_TYPE" = "debs" ] ; then
  while getopts ":s:l:r:nvh" flag ; do
    case $flag in
#TODO      j)	MAKE_JOBS="$OPTARG" ;;			#override auto-detected MAKE_JOBS
      s)	LIVE_SOURCE_BRANCH="$OPTARG" ;;
      l)	LIVE_BUILD_DIR="$OPTARG" ;;			#live/local build directory
      r)	BZR_REVISION="$OPTARG" ;;
      n)	unset UPDATE_OPENCOG ;;				#suppress bzr update
      v)	unset QUIET ;;
      h)	usage ;;
      \?)	usage ;;
    esac
  done
  shift $((OPTIND-1))
elif [ "$SELF_NAME" = "octool" ] || [ "$PACKAGE_TYPE" = "tool" ] ; then
  unset UPDATE_OPENCOG
  while getopts ":j:s:l:r:adubtpvh" flag ; do
    case $flag in     
      j)	MAKE_JOBS="$OPTARG" ;;			#override auto-detected MAKE_JOBS
      s)	LIVE_SOURCE_BRANCH="$OPTARG" ;;  
      l)	LIVE_BUILD_DIR="$OPTARG" ;;		#live/local build directory
      r)	BZR_REVISION="$OPTARG" ;;
      a)	ADD_REPOSITORIES=true ;;
      d)	INSTALL_DEPENDENCIES=true ;;	#ALL, none
      u)	UPDATE_OPENCOG=true ;;			#bzr pull
      b)	BUILD_OPENCOG=true ;;			#TRUE, false : mostly for testing
      t)	TEST_OPENCOG=true ;;			#TRUE, false : mostly for testing
      p)	REINSTALL_PACKAGES=true ;;
      v)	unset QUIET ;;
      h)	usage ;;
      \?)	usage ;;
    esac
  done
  shift $((OPTIND-1))
elif [ "$SELF_NAME" = "oclocal" ] || [ "$PACKAGE_TYPE" = "local" ] ; then
  while getopts ":j:s:l:r:nvh" flag ; do
    case $flag in
      j)	MAKE_JOBS="$OPTARG" ;;			#override auto-detected MAKE_JOBS
      s)	LIVE_SOURCE_BRANCH="$OPTARG" ;;
      l)	LIVE_BUILD_DIR="$OPTARG" ;;		#live build directory
      r)	BZR_REVISION="$OPTARG" ;;
      n)	unset UPDATE_OPENCOG ;;		#suppress bzr update
      v)	unset QUIET ;; 
      h)	usage ;; 
      \?)	usage ;;
    esac
  done
  shift $((OPTIND-1))
elif [ "$SELF_NAME" = "ocmin" ] || [ "$PACKAGE_TYPE" = "min" ] ; then
  while getopts ":i:o:j:s:l:r:nvh" flag ; do
    case $flag in
      i)	INPUT_ISO_NAME="$OPTARG" ;;          
      o)	OUTPUT_ISO_NAME="$OPTARG" ;;          
      j)	MAKE_JOBS="$OPTARG" ;;			#override auto-detected MAKE_JOBS
      s)	LIVE_SOURCE_BRANCH="$OPTARG" ;;   
      l)	LIVE_BUILD_DIR="$OPTARG" ;;		#live build directory
      r)	BZR_REVISION="$OPTARG" ;;
      n)	unset UPDATE_OPENCOG ;;		#suppress bzr update
      v)	unset QUIET ;; 
      h)	usage ;; 
      \?)	usage ;;
    esac
  done
  shift $((OPTIND-1))
elif [ "$SELF_NAME" = "ocdemo" ] || [ "$PACKAGE_TYPE" = "demo" ] ; then
  while getopts ":i:o:j:s:l:r:nvh" flag ; do
    case $flag in
      i)	INPUT_ISO_NAME="$OPTARG" ;;          
      o)	OUTPUT_ISO_NAME="$OPTARG" ;;          
      j)	MAKE_JOBS="$OPTARG" ;;			#override auto-detected MAKE_JOBS
      s)	LIVE_SOURCE_BRANCH="$OPTARG" ;;   
      l)	LIVE_BUILD_DIR="$OPTARG" ;;		#live build directory
      r)	BZR_REVISION="$OPTARG" ;;		
      n)	unset UPDATE_OPENCOG ;;		#suppress bzr update 
      v)	unset QUIET ;; 
      h)	usage ;; 
      \?)	usage ;;
    esac
  done
  shift $((OPTIND-1))
elif [ "$SELF_NAME" = "ocdev" ] || [ "$PACKAGE_TYPE" = "dev" ] ; then
  while getopts ":i:o:j:s:l:r:nvh" flag ; do
    case $flag in
      i)	INPUT_ISO_NAME="$OPTARG" ;;          
      o)	OUTPUT_ISO_NAME="$OPTARG" ;;          
      j)	MAKE_JOBS="$OPTARG" ;;			#override auto-detected MAKE_JOBS
      s)	LIVE_SOURCE_BRANCH="$OPTARG" ;;   
      l)	LIVE_BUILD_DIR="$OPTARG" ;;		#live build directory
      r)	BZR_REVISION="$OPTARG" ;;
      n)	unset UPDATE_OPENCOG ;;		#suppress bzr update
      v)	unset QUIET ;; 
      h)	usage ;; 
      \?)	usage ;;
    esac
  done
  shift $((OPTIND-1))
else
  MESSAGE="$SELF_NAME not recognized." ; message ; usage ; exit 1
fi

#echo "[otheropts]==> $@"

#######################################
# SECTION 3: Error handling & cleanup #
#######################################

debug() {
MESSAGE="Dropping to debugging chroot prompt..." ; message
chroot $LIVE_SQUASH_UNION /bin/bash -l 
}

cleanup_squash() {
if [ -n "$LIVE_SQUASH_UNION" ]; then
  MESSAGE="Cleaning up squash temp space..." ; message
  fuser  $VERBOSE $LIVE_SQUASH_UNION -c -kill
  sleep 1
  umount $VERBOSE $LIVE_SQUASH_UNION/var/lib/apt/lists		|| true
  umount $VERBOSE $LIVE_SQUASH_UNION/var/cache/apt/archives	|| true
  umount $VERBOSE $LIVE_SQUASH_UNION/proc			|| true
  umount $VERBOSE $LIVE_SQUASH_UNION/sys			|| true
  umount $VERBOSE $LIVE_SQUASH_UNION/dev/pts			|| true
  umount $VERBOSE $LIVE_SQUASH_UNION$LIVE_BUILD_DIR		|| true
  umount $VERBOSE $LIVE_SQUASH_UNION$LIVE_SOURCE_BRANCH		|| true
  MESSAGE="Killing processes..." ; message
  fuser  $VERBOSE $LIVE_SQUASH_UNION -c -kill
  sleep  1
  umount -v -f $VERBOSE $LIVE_SQUASH_UNION			|| true
  rmdir  $VERBOSE $LIVE_SQUASH_UNION				|| true
fi

if [ -n "$LIVE_SQUASH_DELTA" ]; then
  echo " $LIVE_SQUASH_DELTA"
  rm -rf $LIVE_SQUASH_DELTA					|| true
fi

if [ -n "$UBUNTU_SQUASH_FILES" ]; then
  echo " $UBUNTU_SQUASH_FILES"
  umount $VERBOSE $UBUNTU_SQUASH_FILES				|| true
  rmdir  $VERBOSE $UBUNTU_SQUASH_FILES				|| true
fi
}

cleanup_iso() {
if [ -n       "$LIVE_ISO_UNION" ] ; then
  MESSAGE="Cleaning up ISO temp space..." ; message
  echo " $LIVE_ISO_UNION"
  umount $VERBOSE $LIVE_ISO_UNION				|| true
  rmdir  $LIVE_ISO_UNION					|| true
  df -m  $LIVE_ISO_UNION					|| true
fi

if [ -n       "$LIVE_ISO_DELTA" ] ; then
  echo " $LIVE_ISO_DELTA"
  rm -rf $LIVE_ISO_DELTA					|| true
fi

if [ -n "$UBUNTU_ISO_FILES" ] ; then
  echo " $UBUNTU_ISO_FILES"
  umount $VERBOSE $UBUNTU_ISO_FILES				|| true
  rmdir  $UBUNTU_ISO_FILES					|| true
  df -m  $UBUNTU_ISO_FILES					|| true
fi
}

exit_trap() {
if [ "$SELF_NAME" != "$TOOL_NAME" ] ; then
  MESSAGE="Exiting $SELF_NAME normally..." ; message
  cleanup_squash
  cleanup_iso
fi
}

quit_trap() {
if [ "$SELF_NAME" != "$TOOL_NAME" ] ; then
  MESSAGE="Exiting $SELF_NAME by request..." ; message
  cleanup_squash
  cleanup_iso
fi
}

error_trap() {
if [ "$SELF_NAME" != "$TOOL_NAME" ] ; then
  MESSAGE="Error trapped while running $SELF_NAME." ; message

  MESSAGE="Cleanup will run after debug." ; message
  debug
  cleanup_squash
  cleanup_iso
fi
}

trap error_trap ERR 
trap exit_trap  EXIT 
trap quit_trap  INT HUP QUIT TERM

###################################
# SECTION 4: Function Definitions #
###################################

add_repositories() {
if [ -f /etc/apt/sources.list.d/opencog-dev-ppa-precise.list ] ; then 
  MESSAGE="opencog-dev software repository exists, skipping adding repositories..." ; message
else
  MESSAGE="Adding software repositories..." ; message
  for REPO in $REPOSITORIES ; do 
    sudo apt-add-repository -y $REPO
  done
  MESSAGE="Updating the package index. Please wait..." ; message
  sudo apt-get $QUIET --assume-yes update 
fi
}

install_admin() {
MESSAGE="Installing sysadmin tools...." ; message
if ! sudo apt-get $QUIET --no-upgrade --assume-yes install $PACKAGES_ADMIN ; then
  MESSAGE="Please enable 'universe' repositories and re-run this script."  ; message
  exit 1
fi
}

install_dependencies() {
MESSAGE="Installing OpenCog build dependencies...." ; message
if ! sudo apt-get $QUIET --no-upgrade --assume-yes install $PACKAGES_BUILD $PACKAGES_RUNTIME ; then
  MESSAGE="Please enable 'universe' repositories and re-run this script."  ; message
  exit 1
fi
}

check_source_dir_exist() {
if [ ! -d $LIVE_SOURCE_BRANCH ] ; then
  MESSAGE="You specified -n option but directory $LIVE_SOURCE_BRANCH does NOT exists. You can use -s option to specify source branch/directory." ; message
  exit 1
fi
}

update_opencog_source() { 
if sudo apt-get --no-upgrade --assume-yes $QUIET install $PACKAGES_FETCH ; then
  echo -n
else
  MESSAGE="Please enable 'universe' repositories and re-run this script."  ; message
exit 1
fi

OPENCOG_SOURCE_DIR=$LIVE_SOURCE_BRANCH
mkdir -p $OPENCOG_SOURCE_DIR || true
if [ ! "$(ls -A $OPENCOG_SOURCE_DIR)" ]; then
  MESSAGE="Fetching OpenCog source at $OPENCOG_SOURCE_DIR..." ; message
  bzr branch https://code.launchpad.net/opencog --use-existing-dir $OPENCOG_SOURCE_DIR -r $BZR_REVISION
else
  # It seems this 'if' test is not needed (as the call to update_opencog_source() is surrounded by similar 'if' test). Test it!
  #if [ $UPDATE_OPENCOG ] ; then
    MESSAGE="Updating OpenCog source at $OPENCOG_SOURCE_DIR..." ; message
    bzr pull https://code.launchpad.net/opencog --directory $OPENCOG_SOURCE_DIR -r $BZR_REVISION
  #fi
fi
}

build_opencog() {
mkdir -p -v $LIVE_BUILD_DIR || true
cd $LIVE_BUILD_DIR
MESSAGE="cmake $LIVE_SOURCE_BRANCH" ; message
cmake $LIVE_SOURCE_BRANCH
MESSAGE="make -j$MAKE_JOBS" ; message
make -j$MAKE_JOBS

if [ $TEST_OPENCOG ] ; then 
  make test
fi

case $PACKAGE_TYPE in
  min)	MESSAGE="Installing OpenCog..." ; message
 	make install; exit 0;;
  demo)	MESSAGE="Installing OpenCog..." ; message
  	make install; exit 0;;
  dev)	exit 0;;
esac

}

locate_live_iso() {
if [ $INPUT_ISO_NAME ]; then 
  MESSAGE="Using Ubuntu image specified at $INPUT_ISO_NAME" ; message
  UBUNTU_ISO_IMAGE=$INPUT_ISO_NAME
else 
  UBUNTU_LOCATIONS=$(locate --existing --basename "\\$UBUNTU_ISO" | grep $HOME)
  for LOC in $UBUNTU_LOCATIONS ; do
    MESSAGE="Ubuntu image found at $LOC. Checksumming, please wait..." ; message
    LOC_MD5SUM=$(md5sum $LOC | awk '{print $1}')
  if [ "$LOC_MD5SUM" == "$UBUNTU_MD5SUM" ] ; then
    UBUNTU_ISO_IMAGE=$LOC
    MESSAGE="Using image found at $UBUNTU_ISO_IMAGE." ; message
    break 
  else
    MESSAGE="...checksum failed." ; message
  fi 
done 
fi
if [ ! -f $UBUNTU_ISO_IMAGE ] ; then
 aria2c --seed-time=0 ${UBUNTU_URL}${UBUNTU_ISO}.torrent
 UBUNTU_ISO_IMAGE=${UBUNTU_ISO}
fi
}

remove_packages() {
MESSAGE="$PACKAGE_TYPE install type: Removing unecessary packages..." ; message
chroot $LIVE_SQUASH_UNION apt-get --no-upgrade --assume-yes $QUIET purge $PACKAGES_REMOVE --auto-remove 
chroot $LIVE_SQUASH_UNION apt-get --no-upgrade --assume-yes $QUIET autoremove
}

reinstall_removed() {
MESSAGE="Re-installing removed packages..." ; message
apt-get --no-upgrade --assume-yes $QUIET install $PACKAGES_REMOVE
}

keep_source() {
MESSAGE="$PACKAGE_TYPE install type: Keeping source code..." ; message 
chroot $LIVE_SQUASH_UNION chown -R 999 $LIVE_SOURCE_BRANCH $LIVE_BUILD_DIR	 #999=ubuntu user
chroot $LIVE_SQUASH_UNION mkdir -p /home/$LIVE_USERNAME/Desktop/
chroot $LIVE_SQUASH_UNION ln -s "$LIVE_SOURCE_BRANCH" "/home/$LIVE_USERNAME/Desktop/$LIVE_DESKTOP_SOURCE" || true
}

remove_source() {
MESSASGE="$PACKAGE_TYPE install type: Removing source code..." ; message
chroot $LIVE_SQUASH_UNION umount $VERBOSE $LIVE_SOURCE_BRANCH	
}

remove_build() {
MESSAGE="$PACKAGE_TYPE install type: Removing build files..." ; message 
echo umount $VERBOSE $LIVE_SQUASH_UNION$LIVE_BUILD_DIR 
umount $VERBOSE $LIVE_SQUASH_UNION$LIVE_BUILD_DIR || true 	
rm -rf $LIVE_SQUASH_UNION$LIVE_BUILD_DIR || true
}

remove_dev_debs() {
MESSAGE="$PACKAGE_TYPE install type: Removing development packages..." ; message 
#chroot $LIVE_SQUASH_UNION apt-get $QUIET -y remove $PACKAGES_BUILD $PACKAGES_EXDEV --auto-remove 
chroot $LIVE_SQUASH_UNION apt-get --no-upgrade --assume-yes purge $PACKAGES_BUILD $PACKAGES_EXDEV --auto-remove 
chroot $LIVE_SQUASH_UNION apt-get $QUIET autoremove
}

remove_doc_debs() {
MESSAGE="$PACKAGE_TYPE install type: Removing documentation packages..." ; message 
chroot $LIVE_SQUASH_UNION apt-get --no-upgrade --assume-yes purge $PACKAGES_DOC --auto-remove 
chroot $LIVE_SQUASH_UNION apt-get $QUIET autoremove
}

install_package_tools() {
MESSAGE="Installing packaging tools..." ; message
if sudo apt-get --no-upgrade --assume-yes $QUIET -y install $PACKAGES_TOOLS ; then
 echo -n
else
 MESSAGE="Please enable 'universe' repositories and re-run this script."  ; message
 exit 1
fi
}

install_deb_package_tools() {
MESSAGE="Installing DEB packaging tools..." ; message
if ! sudo apt-get --no-upgrade --assume-yes $QUIET -y install $DEB_PACKAGES_TOOLS ; then
 MESSAGE="Please enable 'universe' repositories and re-run this script."  ; message
 exit 1
fi
}

build_opencog_deb() {
DEB_BUILD_DIR=$LIVE_BUILD_DIR
mkdir -p -v $DEB_BUILD_DIR || true
cd $DEB_BUILD_DIR
# lp:opencog contains Gama's debian/ in the root directory. It needs to be manually deleted before creating upstream source tar
cp -r $LIVE_SOURCE_BRANCH /tmp/opencog_temp
rm -rf /tmp/opencog-temp/debian/

MESSAGE="Creating OpenCog (upstream) source tarball..." ; message
bzr export opencog-0.1.tar.gz /tmp/opencog_temp
# Cleanup
rm -rf /tmp/opencog_temp

# Extract upstream source tarball and auto-add debian/ template
# TODO: OpenCog versions
MESSAGE="Extracting upstream source (OpenCog) tarball and debianizing it..." ; message
tar -xzf opencog-0.1.tar.gz
cd opencog-0.1
#rm -rf debian/


# Using dh_make: All that dh_make does is:
# 1. create a orig tarball (opencog-orig.tar.gz)
# 2. create a debian/ template directory in the branch
# This is manually done by this ocpkg using two simple 'cp' commands.
#echo "\n" | dh_make --email test@example.com -s -f ../opencog-0.1.tar.gz

# Delete auto-added debian/ templates (created by 'dh_make')
#rm -rf debian/


# Without dh_make (i.e. manually doing what dh_make does behind the scenes):
# Fully automated (as opposed to dh_make solution above)
# Create orig if not using dh_make
cp ../opencog-0.1.tar.gz ../opencog_0.1.orig.tar.gz

# Use customized debianization: add customized debian/ config (from amberj-ocpkg)
# TODO: When code in amberj-ocpkg is merged with lp:ocpkg, following line should be modified to work with lp:ocpkg
bzr branch lp:~i-amber-jain/ocpkg/amberj-ocpkg /tmp/amberj-ocpkg -r $BZR_REVISION
cp -r /tmp/amberj-ocpkg/debian/ .
rm -rf /tmp/amberj-ocpkg
#cd opencog

# Create DEB packages
# -us -uc imply not to (gpg) sign the packages
debuild -us -uc
cd ..

echo "FINISHED! You'll find packages (*.deb) in $DEB_BUILD_DIR"
#echo "Run 'ls -l /tmp/*.deb' to see a list of all DEBs created."
#echo "Use 'sudo dpkg -i PACKAGE_NAME.deb' to install and 'sudo dpkg -r PACKAGE_NAME.deb' to uninstall any package."
}

mount_live_iso() {
MESSAGE="Mounting Ubuntu ISO image..." ; message

UBUNTU_ISO_FILES=$(mktemp -d --suffix=.UBUNTU_ISO_FILES)
mount $VERBOSE -o ro -o loop -t iso9660 $UBUNTU_ISO_IMAGE $UBUNTU_ISO_FILES

MESSAGE="Mounting Ubuntu compressed filesystem..." ; message

UBUNTU_SQUASH_BLOB="$UBUNTU_ISO_FILES/casper/filesystem.squashfs"

if ! [ -e "$UBUNTU_SQUASH_BLOB" ] ; then
  MESSAGE="Could not find the Ubuntu squashfs at '$UBUNTU_SQUASH_BLOB'." ; message
  umount $VERBOSE $UBUNTU_ISO_FILES || true
  exit 1
fi

LIVE_ISO_DELTA=$(mktemp -d --suffix=.LIVE_ISO_DELTA)
LIVE_ISO_UNION=$(mktemp -d --suffix=.LIVE_ISO_UNION)
mount $VERBOSE -t aufs -o br=$LIVE_ISO_DELTA:$UBUNTU_ISO_FILES none $LIVE_ISO_UNION

#MESSAGE="Mounting read-only Ubuntu compressed filesystem..." ; message

UBUNTU_SQUASH_FILES=$(mktemp -d --suffix=.UBUNTU_SQUASH_FILES)
mount $VERBOSE -o loop -t squashfs $UBUNTU_SQUASH_BLOB $UBUNTU_SQUASH_FILES

#MESSAGE="Creating temporary workplace for remastering new compressed files..." ; message

LIVE_SQUASH_DELTA=$(mktemp -d --suffix=.LIVE_SQUASH_DELTA)
LIVE_SQUASH_UNION=$(mktemp -d --suffix=.LIVE_SQUASH_UNION)
mount $VERBOSE -t aufs -o br=$LIVE_SQUASH_DELTA:$UBUNTU_SQUASH_FILES none $LIVE_SQUASH_UNION

MESSAGE="Setting up chroot environment..." ; message

DISTRIB_ID=$(awk '/DISTRIB_ID=/' $LIVE_SQUASH_UNION/etc/lsb-release | sed 's/DISTRIB_ID=//' | tr '[:upper:]' '[:lower:]')
DISTRIB_CODENAME=$(awk '/DISTRIB_CODENAME=/' $LIVE_SQUASH_UNION/etc/lsb-release | sed 's/DISTRIB_CODENAME=//' | tr '[:upper:]' '[:lower:]')
LIVE_USERNAME=$DISTRIB_ID
LIVE_BUILD_DIR=/home/$LIVE_USERNAME/build

cp $LIVE_SQUASH_UNION/etc/resolv.conf      $LIVE_SQUASH_UNION/etc/resolv.conf.bak || true
cp $LIVE_SQUASH_UNION/etc/apt/sources.list $LIVE_SQUASH_UNION/etc/apt/sources.list.bak || true
cp /etc/resolv.conf      $LIVE_SQUASH_UNION/etc
cp /etc/apt/sources.list $LIVE_SQUASH_UNION/etc/apt
if [ -f /etc/apt/apt.conf.d/01apt-cacher-ng-proxy ] ; then
 cp /etc/apt/apt.conf.d/01apt-cacher-ng-proxy  $LIVE_SQUASH_UNION/etc/apt/apt.conf.d/01apt-cacher-ng-proxy
fi

cp $0 $LIVE_SQUASH_UNION$PATH_PREFIX/bin/$SELF_NAME ; chmod ugo+rx $LIVE_SQUASH_UNION$PATH_PREFIX/bin/$SELF_NAME
cd $LIVE_SQUASH_UNION$PATH_PREFIX/bin
ln -s $SELF_NAME $TOOL_NAME
cd $CURRENT_DIR

MESSAGE="Mounting filesystems..." ; message

chroot $LIVE_SQUASH_UNION mount $VERBOSE -t proc none /proc
chroot $LIVE_SQUASH_UNION mount $VERBOSE -t sysfs none /sys
chroot $LIVE_SQUASH_UNION mount $VERBOSE -t devpts none /dev/pts

mkdir -p $LIVE_SQUASH_UNION/$LIVE_SOURCE_BRANCH

mount $VERBOSE -t aufs -o br=/var/cache/apt/archives none $LIVE_SQUASH_UNION/var/cache/apt/archives
mount $VERBOSE -t aufs -o br=/var/lib/apt/lists none $LIVE_SQUASH_UNION/var/lib/apt/lists
# Replaced $HOST_SOURCE_BRANCH with $ LIVE_SOURCE_BRANCH below (since the whole ocpkg script uses LIVE_SOURCE_BRANCH instead)
# TODO: Test if code/line below workds with $LIVE_SOURCE_BRANCH? Test and edit accordingly
mount $VERBOSE -t aufs -o br=$LIVE_SOURCE_BRANCH none $LIVE_SQUASH_UNION/$LIVE_SOURCE_BRANCH
}

prepare_live_iso() {

echo     fuser $LIVE_SQUASH_UNION -c -kill
fuser  $VERBOSE $LIVE_SQUASH_UNION -c -kill
sleep 1
umount $VERBOSE $LIVE_SQUASH_UNION/proc || true
umount $VERBOSE $LIVE_SQUASH_UNION/sys || true
umount $VERBOSE $LIVE_SQUASH_UNION/dev/pts|| true
umount $VERBOSE $LIVE_SQUASH_UNION/var/lib/apt/lists || true
umount $VERBOSE $LIVE_SQUASH_UNION/var/cache/apt/archives || true

#replace original config files
cp $LIVE_SQUASH_UNION/etc/resolv.conf.bak      $LIVE_SQUASH_UNION/etc/resolv.conf || true
cp $LIVE_SQUASH_UNION/etc/apt/sources.list.bak $LIVE_SQUASH_UNION/etc/apt/sources.list || true

if [ -f  $LIVE_SQUASH_UNION/etc/apt/apt.conf.d/01apt-cacher-ng-proxy ]; then
  rm $LIVE_SQUASH_UNION/etc/apt/apt.conf.d/01apt-cacher-ng-proxy
fi
}

write_live_media() {
MESSAGE="Creating new compressed filesystem..." ; message
mksquashfs $LIVE_SQUASH_UNION $LIVE_ISO_UNION/casper/filesystem.squashfs $SQUASHFS_OPTIONS 
printf $(sudo du -sx --block-size=1 $LIVE_SQUASH_UNION | cut -f1) > $LIVE_ISO_UNION/casper/filesystem.size
MESSAGE="Creating new bootable ISO image..." ; message
mkisofs -D -r -V $OUTPUT_ISO_LOCATION/$OUTPUT_ISO_NAME -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o "$OUTPUT_ISO_LOCATION/$OUTPUT_ISO_NAME" $LIVE_ISO_UNION
MESSAGE="Wrote $(du -sm $OUTPUT_ISO_LOCATION/$OUTPUT_ISO_NAME)MB ..." ; message
chown $VERBOSE $SUDO_USER $OUTPUT_ISO_LOCATION/$OUTPUT_ISO_NAME
cleanup_squash
cleanup_iso
}

#######################################
# SECTION 5: Main Program (MAIN main) #
#######################################

if [ "$SELF_NAME" = "ocdebs" ] || [ "$PACKAGE_TYPE" = "debs" ] ; then
  install_deb_package_tools ; add_repositories ; install_dependencies
  if [ $UPDATE_OPENCOG ] ; then update_opencog_source ; else check_source_dir_exist ; fi
  build_opencog_deb
elif [ "$SELF_NAME" = "octool" ] || [ "$PACKAGE_TYPE" = "tool" ] ; then
  if [ $ADD_REPOSITORIES ] ; then add_repositories ; fi 
  if [ $INSTALL_DEPENDENCIES ] ; then install_dependencies ; fi 
  if [ $UPDATE_OPENCOG ] ; then update_opencog_source ; fi
  if [ $BUILD_OPENCOG ] ; then build_opencog ; fi
  if [ $REINSTALL_PACKAGES ] ; then reinstall_removed ; fi
elif [ "$SELF_NAME" = "oclocal" ] || [ "$PACKAGE_TYPE" = "local" ] ; then
  add_repositories ; install_dependencies
  if [ $UPDATE_OPENCOG ] ; then update_opencog_source ; else check_source_dir_exist ; fi
  build_opencog
elif [ "$SELF_NAME" = "ocmin" ] || [ "$PACKAGE_TYPE" = "min" ] ; then
  install_package_tools ; locate_live_iso ; mount_live_iso ; remove_packages
  chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -a -d
  if [ $UPDATE_OPENCOG ] ; then chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -u ; fi
  chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -b
  remove_dev_debs ; remove_doc_debs ; remove_source ; remove_build ; prepare_live_iso ; write_live_media
elif [ "$SELF_NAME" = "ocdemo" ] || [ "$PACKAGE_TYPE" = "demo" ] ; then
  install_package_tools ; locate_live_iso ; mount_live_iso ; remove_packages
  chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -a -d
  if [ $UPDATE_OPENCOG ] ; then chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -u ; fi
  chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -b
  remove_dev_debs ; remove_doc_debs ; remove_source ; remove_build ; prepare_live_iso ; write_live_media
elif [ "$SELF_NAME" = "ocdev" ] || [ "$PACKAGE_TYPE" = "dev" ] ; then
  install_package_tools ; locate_live_iso ; mount_live_iso
  MESSAGE="$PACKAGE_TYPE install type: Keeping all Ubuntu pakagkes..." ; message
  chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -a -d
  if [ $UPDATE_OPENCOG ] ; then chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -u ; fi
  chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -b
  keep_source ; prepare_live_iso ; write_live_media
else
  MESSAGE="Could not recognize package type" ; message ; usage ; exit 1
fi

# package type selected when invoked as 'ocpkg'

#case $PACKAGE_TYPE in
#  debs) install_deb_package_tools ;;
#  demo)	install_package_tools; locate_live_iso ; mount_live_iso ; remove_packages ;;
#  min)	install_package_tools; locate_live_iso ; mount_live_iso ; remove_packages ;;
#  dev)	install_package_tools; locate_live_iso ; mount_live_iso 
#      	MESSAGE="$PACKAGE_TYPE install type: Keeping all Ubuntu pakagkes..." ; message ;;
#esac
#
#case $PACKAGE_TYPE in
#  local) add_repositories ; install_dependencies ;;
#  debs)  add_repositories ; install_dependencies ;;
#  demo)  chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -a -d ;;
#  min)   chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -a -d ;;
#  dev)   chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -a -d ;;
#esac
#
#case $PACKAGE_TYPE in
#  local) if [ $UPDATE_OPENCOG ] ; then update_opencog_source ; else check_source_dir_exist ; fi ;;
#  debs)  if [ $UPDATE_OPENCOG ] ; then update_opencog_source ; else check_source_dir_exist ; fi ;;
#  demo)  if [ $UPDATE_OPENCOG ] ; then chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -u ; fi ;;
#  min)   if [ $UPDATE_OPENCOG ] ; then chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -u ; fi ;;
#  dev)   if [ $UPDATE_OPENCOG ] ; then chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -u ; fi ;;
#esac
#
#case $PACKAGE_TYPE in
#  local) if [ $BUILD_OPENCOG ] ; then build_opencog ; fi ;;
#  debs)  if [ $BUILD_OPENCOG ] ; then build_opencog_deb ; fi ;;
#  demo)  if [ $BUILD_OPENCOG ] ; then chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -b ; fi ;;
#  min)   if [ $BUILD_OPENCOG ] ; then chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -b ; fi ;;
#  dev)   if [ $BUILD_OPENCOG ] ; then chroot $LIVE_SQUASH_UNION $PATH_PREFIX/bin/$TOOL_NAME -b ; fi ;;
#esac
#
#case $PACKAGE_TYPE in
#  min)	remove_dev_debs ; remove_doc_debs ; remove_source ; remove_build ;;
#  demo)	remove_dev_debs ; remove_doc_debs ; remove_source ; remove_build ;;
#  dev)	keep_source  ;;
#esac
#
#case $PACKAGE_TYPE in
#  min)  prepare_live_iso ; write_live_media ;;
#  demo) prepare_live_iso ; write_live_media ;;
#  dev)  prepare_live_iso ; write_live_media ;;
#esac
