.TH "ocpkg" 8 "2012 Jul 05" "Debian" "pbuilder"
.SH NAME
ocpkg \- download, build, test, install and package OpenCog
.SH SYNOPSIS
.BI "ocpkg --deb [" "options" "]"
.PP
.BI "ocpkg --tool [" "options" "]"
.PP
.BI "ocpkg --local [" "options" "]"
.PP
.BI "ocpkg --ppa [" "options" "]"
.PP
.BI "ocpkg --dailybuild"
.SH "DESCRIPTION"
Front end program to the 
.B "ocpkg"
suite of bash scripts used to download, build, test, install and package
OpenCog.

.SH "COMMANDS"

.TP
.B "--deb"
Create 
.B "DEB" 
packages for Debian based systems (including Ubuntu).

.TP
.B "--tool"
Common building/packaging operations for OpenCog.

.TP
.B "--local"
[TBD] Build the package locally.

.TP
.B "--ppa"
[TBD] Create OpenCog source package and upload it to Launchpad PPA.

.TP
.B "--dailybuild"
[TBD] Build the package locally in a daily build environment.

.SH "OPTIONS"

.TP
To be done.

.SH "FILES"

.TP
To be done.

.SH "EXAMPLES"

.TP
.B "./ocpkg --deb"

.TP
.B "./ocpkg --tool"

.SH "BUGS"
Not known.

.SH "AUTHORS"
To be done.

OpenCog homepage is located at
.B "\%http://opencog.org/"

The currently active development branches are located at
.B "\%https://launchpad.net/ocpkg"
and
.B "\%https://code.launchpad.net/~i-amber-jain/ocpkg/amberj-ocpkg"

.SH "SEE ALSO"
To be done: 
.BR "ocdeb" "(8), "
.BR "octool" "(8), "
.BR "oclocal" "(8), "
.BR "ocppa" "(8), "
.BR "ocdaily" "(8)"


\"  LocalWords:  buildresult
