#!/bin/bash
#
## @file		octool
## @copyright		OpenCog Foundation (2012)
## @author		David Hart <dhart@opencog.org>
## @section DESCRIPTION	A script to perform common operations for building/packaging OpenCog
## @section LICENSE	Permission to copy and modify is granted under the GPL
## @section REQUIREMENT	Ubuntu Linux 12.04 (precise pangolin)
## @section SEEALSO	ocbootstrap - install an Ubuntu chroot on any Linux distro

while getopts ":adubtpv" flag ; do
  case $flag in
    a)	ADD_REPOSITORIES=true ;;
    d)	INSTALL_DEPENDENCIES=true ;;		#ALL, none
    u)	UPDATE_OPENCOG=true ;;			#bzr pull
    b)	BUILD_OPENCOG=true ;;			#TRUE, false : mostly for testing
    t)	TEST_OPENCOG=true ;;			#TRUE, false : mostly for testing
    p)	REINSTALL_PACKAGES=true ;; 
    v)	unset QUIET ;; 
  esac
done

shift $((OPTIND-1))

if [ $ADD_REPOSITORIES ] ; then add_repositories ; fi 
if [ $INSTALL_DEPENDENCIES ] ; then install_dependencies ; fi 
if [ $UPDATE_OPENCOG ] ; then update_opencog_source ; fi
if [ $BUILD_OPENCOG ] ; then build_opencog ; fi
if [ $REINSTALL_PACKAGES ] ; then reinstall_removed ; fi
